spring:
  application:
    name: back-office
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backoffice_db}
    username: ${SPRING_DATASOURCE_USERNAME:backoffice_user}
    password: ${SPRING_DATASOURCE_PASSWORD:backoffice_pwd}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
