spring:
  application:
    name: back-office
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/visa_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

app:
  # Utiliser l'IP locale (ex: http://192.168.1.10:4200) pour que le QR fonctionne sur mobile.
  frontend-base-url: ${APP_FRONTEND_BASE_URL:http://192.168.9.196:4200}

management:
  endpoints:
    web:
      exposure:
        include: health,info
