-- Obsolete : les colonnes photo_identite / signature_digital ne sont plus sur demandeur.
-- Voir sql/schemas/19-05-2026.sql et les lignes catalogue piece_justificative + demande_piece_justificative.
